---

- hosts: all
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2    
    apt:
      name: apache2
      state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname
    shell: echo "<h1>I'm popularly called $(hostname -f) a.k.a the host and your'e viewing this today-$(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted